spring:
  config:
    activate:
      on-profile:
        - dev

  mariadb:
    console:
      enabled: true
      path: /mariadb-console

  datasource:
    username: weatherapp_db
    password: weatherapp_user
    url: jdbc:mariadb://localhost:3306/weatherapp_db
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: weatherapp_db
    password: weatherapp_user
    url: jdbc:mariadb://localhost:3306/weatherapp_db
    change-log: classpath:db/master.xml
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com.meawallet.weatherapp: DEBUG

weather-api:
  weather-url: https://api.met.no/weatherapi/locationforecast/2.0/compact?lat={latitude}&lon={longitude}

server:
  error:
    include-message: always
  port: 8081
