spring:
  config:
    activate:
      on-profile:
        - dev

  mariadb:
    console:
      enabled: true
      path: /mariadb-console

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    change-log: classpath:db/master.xml

logging:
  level:
    com.meawallet.weatherapp: DEBUG

weather-api:
  weather-url: https://api.met.no/weatherapi/locationforecast/2.0/compact?lat={latitude}&lon={longitude}

server:
  error:
    include-message: always
  port: ${WEATHERAPP_PORT}