name: SonarQube Analysis

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Start SonarQube Docker container
        run: |
          docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
          # Wait for SonarQube to start (adjust sleep time as needed)
          sleep 30

      - name: Build and analyze with Gradle
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.NOVUSS_SYSTEM_AUTH_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew sonarqube

      - name: Stop and remove SonarQube Docker container
        run: |
          docker stop sonarqube
          docker rm sonarqube
